backend:
  name: github
  repo: IHCC-Cyber-Club/Club-Website
  branch: main
  base_url: https://test-site-ruby-tau.vercel.app
  auth_endpoint: /api/auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "meeting_notes"
    label: "Meeting Notes"
    folder: "content/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Minutes", name: "body", widget: "markdown" }